"""
Ablation: News Sentiment Removed.

Reviewer #4 (ESWA-D-26-08980) argued that LLM-based sentiment is noisy,
delayed, and linguistically ambiguous, so its real contribution to the
trading system is questionable.

This ablation **removes the news-sentiment branch** of the feature
fusion layer at inference time by zeroing the sentiment columns of the
unified state vector. Everything else (regime classifier, PPO agents,
ensemble) stays unchanged, isolating the marginal benefit of news.

Use together with :mod:`scripts.run_ablation_no_news` to obtain a
clean before/after comparison.
"""

from __future__ import annotations

import logging
from typing import Iterable

import numpy as np
import pandas as pd

logger = logging.getLogger(__name__)


# Column-name prefixes generated by NewsSentimentExtractor /
# FinBERTSentimentExtractor + FeatureFusion.
_DEFAULT_SENTIMENT_PREFIXES = (
    "sentiment_",
    "news_",
    "positive_count",
    "neutral_count",
    "negative_count",
    "p_positive",
    "p_negative",
    "p_neutral",
)


def detect_sentiment_columns(
    state_data: pd.DataFrame,
    prefixes: Iterable[str] = _DEFAULT_SENTIMENT_PREFIXES,
) -> list:
    return [
        c
        for c in state_data.columns
        if any(str(c).startswith(p) for p in prefixes)
    ]


def zero_out_news_features(
    state_data: pd.DataFrame,
    prefixes: Iterable[str] = _DEFAULT_SENTIMENT_PREFIXES,
) -> pd.DataFrame:
    """
    Return a copy of ``state_data`` with all sentiment-related columns
    set to zero. Non-sentiment features are preserved bit-for-bit.
    """
    cols = detect_sentiment_columns(state_data, prefixes)
    if not cols:
        logger.warning(
            "no_news ablation: no sentiment-like columns matched. "
            "Returning unchanged DataFrame."
        )
        return state_data.copy()
    masked = state_data.copy()
    masked.loc[:, cols] = 0.0
    logger.info(
        "no_news ablation: zeroed %d sentiment columns (%s ...).",
        len(cols),
        cols[:4],
    )
    return masked


__all__ = [
    "detect_sentiment_columns",
    "zero_out_news_features",
]
