"""Aggregate side-by-side comparison of v1-baseline / reward-only-v2 /
full-v2 walk-forward runs.

Inputs
------
- ``results/walk_forward/summary.json``                    # v1 baseline
- ``results/walk_forward_reward_v2/summary.json``          # reward-only v2
- ``results/walk_forward_reward_v2_full/summary.json``     # full v2

Output
------
- ``results/walk_forward_v2_comparison.md``  (markdown report)
- ``results/figures/fig_v1_v2_comparison.png``  (bar chart)

Run after both v2 walk-forwards complete; the script skips the
combined-v2 column if the file is missing so the report can still
be regenerated immediately after the reward-only run finishes.
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import matplotlib.pyplot as plt
import matplotlib.ticker as mtick
import numpy as np

PROJECT_ROOT = Path(__file__).resolve().parents[1]
FIG_DIR = PROJECT_ROOT / "results" / "figures"
FIG_DIR.mkdir(parents=True, exist_ok=True)
OUT_MD = PROJECT_ROOT / "results" / "walk_forward_v2_comparison.md"

RUNS: List[Tuple[str, Path]] = [
    ("v1 baseline",        PROJECT_ROOT / "results" / "walk_forward" / "summary.json"),
    ("reward-only v2",     PROJECT_ROOT / "results" / "walk_forward_reward_v2" / "summary.json"),
    ("full v2 (rwd+clf+nv)", PROJECT_ROOT / "results" / "walk_forward_reward_v2_full" / "summary.json"),
]

METRIC_ORDER = [
    "Sharpe Ratio",
    "Cumulative Return",
    "CAGR",
    "Maximum Drawdown",
    "Win Rate",
    "Profit Factor",
]


def _load(p: Path) -> Optional[Dict]:
    if not p.exists():
        return None
    with open(p, "r", encoding="utf-8") as f:
        return json.load(f)


def _fold_metrics(d: Dict) -> Dict[str, List[float]]:
    """Return {metric: [fold1, fold2, ...]} aligned to the metric order."""
    out: Dict[str, List[float]] = {k: [] for k in METRIC_ORDER}
    folds = sorted(d["folds"], key=lambda f: f["fold"])
    for f in folds:
        for k in METRIC_ORDER:
            out[k].append(float(f["metrics"].get(k, np.nan)))
    return out


def _mean_std(values: List[float]) -> Tuple[float, float]:
    arr = np.array(values, dtype=float)
    arr = arr[~np.isnan(arr)]
    if len(arr) == 0:
        return (np.nan, np.nan)
    return (float(np.mean(arr)),
            float(np.std(arr, ddof=1)) if len(arr) > 1 else 0.0)


def build_table() -> Tuple[List[str], Dict[str, Dict[str, Tuple[float, float]]]]:
    """Return ``(present_run_names, {metric: {run: (mean, std)}})``."""
    present: List[str] = []
    table: Dict[str, Dict[str, Tuple[float, float]]] = {k: {} for k in METRIC_ORDER}
    for name, path in RUNS:
        d = _load(path)
        if d is None:
            continue
        present.append(name)
        m = _fold_metrics(d)
        for metric in METRIC_ORDER:
            table[metric][name] = _mean_std(m[metric])
    return present, table


def write_markdown(present: List[str], table: Dict[str, Dict[str, Tuple[float, float]]]) -> None:
    lines = ["# Walk-Forward Comparison — v1 baseline vs v2 ablations",
             "",
             f"Generated by `scripts/_compare_v1_v2_walk_forward.py`. "
             f"Each cell is `mean ± std` over the available walk-forward folds.",
             ""]
    if not present:
        lines.append("**No runs available.**")
        OUT_MD.write_text("\n".join(lines), encoding="utf-8")
        return

    header = "| Metric | " + " | ".join(present) + " |"
    sep = "|--------|" + "|".join(["------:"] * len(present)) + "|"
    lines.append(header)
    lines.append(sep)
    for metric in METRIC_ORDER:
        row = [metric]
        for name in present:
            ms = table[metric].get(name)
            if ms is None or np.isnan(ms[0]):
                row.append("—")
            else:
                row.append(f"{ms[0]:.4f} ± {ms[1]:.4f}")
        lines.append("| " + " | ".join(row) + " |")

    lines.append("")
    lines.append("### Per-fold cumulative return")
    lines.append("")
    lines.append("| Fold | " + " | ".join(present) + " |")
    lines.append("|------|" + "|".join(["------:"] * len(present)) + "|")
    # Pull per-fold cumulative return per run.
    fold_table: Dict[int, Dict[str, float]] = {}
    for name, path in RUNS:
        d = _load(path)
        if d is None:
            continue
        for f in d["folds"]:
            fold_table.setdefault(f["fold"], {})[name] = (
                float(f["metrics"]["Cumulative Return"]) * 100
            )
    for fid in sorted(fold_table):
        row = [str(fid)]
        for name in present:
            v = fold_table[fid].get(name)
            row.append(f"{v:+.2f}%" if v is not None else "—")
        lines.append("| " + " | ".join(row) + " |")

    OUT_MD.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT_MD}")


def write_figure(present: List[str], table: Dict[str, Dict[str, Tuple[float, float]]]) -> None:
    if not present:
        return

    fig, ax = plt.subplots(figsize=(8.5, 4.5))
    width = 0.8 / max(len(present), 1)
    metrics_to_plot = ["Sharpe Ratio", "Cumulative Return", "Win Rate", "Profit Factor"]
    x = np.arange(len(metrics_to_plot))
    palette = ["#bbbbbb", "#d65f5f", "#4878d0"]
    for i, name in enumerate(present):
        means = [table[m][name][0] if name in table[m] else np.nan for m in metrics_to_plot]
        stds = [table[m][name][1] if name in table[m] else 0.0 for m in metrics_to_plot]
        offset = (i - (len(present) - 1) / 2) * width
        ax.bar(x + offset, means, yerr=stds, width=width,
               label=name, color=palette[i % len(palette)],
               error_kw=dict(ecolor="black", lw=1, capsize=3))
    ax.set_xticks(x)
    ax.set_xticklabels(metrics_to_plot)
    ax.axhline(0, color="black", lw=0.5)
    ax.set_title("Walk-Forward mean across 5 folds  —  v1 baseline vs v2")
    ax.set_ylabel("Value (raw)")
    ax.legend(loc="upper right", fontsize=8)
    fig.tight_layout()
    out_png = FIG_DIR / "fig_v1_v2_comparison.png"
    fig.savefig(out_png, dpi=200, bbox_inches="tight")
    plt.close(fig)
    print(f"Wrote {out_png}")


def main() -> int:
    present, table = build_table()
    write_markdown(present, table)
    write_figure(present, table)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
