"""
FinBERT-based news sentiment extractor.

Reviewer #3 (ESWA-D-26-08980) raised a "Look-ahead Bias" concern because
the original sentiment column in `cryptonews_2021-10-12_2023-12-19.csv`
was generated by a 2025-released LLM (DeepSeek), which post-dates the
backtest window (2021-10-12 ~ 2023-12-19).

This module re-generates sentiment scores using **FinBERT**
(`ProsusAI/finbert`, publicly released 2019-08), which strictly predates
the backtest period and therefore eliminates the look-ahead bias.

If `transformers` / `torch` are unavailable, the extractor falls back to
the original CSV polarity (with a warning) so the pipeline keeps working.
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Iterable, List, Optional

import numpy as np
import pandas as pd

logger = logging.getLogger(__name__)


_DEFAULT_MODEL_NAME = "ProsusAI/finbert"
_LABEL_ORDER = ("positive", "negative", "neutral")


class FinBERTSentimentExtractor:
    """
    Re-score news headlines with FinBERT to remove look-ahead bias.

    Output schema is identical to the legacy CSV so downstream modules
    (`NewsSentimentExtractor`, `FeatureExtractor`) need no changes:

      - sentiment_class      : 'positive' | 'neutral' | 'negative'
      - sentiment_polarity   : p(positive) - p(negative)  in [-1, +1]
      - sentiment_subjectivity : 1 - p(neutral)            in [0, 1]

    Parameters
    ----------
    model_name : str
        HuggingFace model id. Default = 'ProsusAI/finbert'.
    device : str
        'cpu' or 'cuda'. Defaults to CPU for portability.
    batch_size : int
        Inference batch size.
    max_length : int
        Token truncation length (FinBERT supports up to 512).
    """

    def __init__(
        self,
        model_name: str = _DEFAULT_MODEL_NAME,
        device: str = "cpu",
        batch_size: int = 32,
        max_length: int = 256,
    ) -> None:
        self.model_name = model_name
        self.device = device
        self.batch_size = batch_size
        self.max_length = max_length

        self._tokenizer = None
        self._model = None
        self._torch = None
        self._available = self._try_load_model()

    def _try_load_model(self) -> bool:
        """Attempt to load FinBERT; return False if unavailable."""
        try:
            import torch
            from transformers import (
                AutoModelForSequenceClassification,
                AutoTokenizer,
            )
        except ImportError as exc:
            logger.warning(
                "FinBERT dependencies missing (%s). "
                "Fallback to legacy CSV polarity.",
                exc,
            )
            return False

        try:
            self._torch = torch
            self._tokenizer = AutoTokenizer.from_pretrained(self.model_name)
            self._model = AutoModelForSequenceClassification.from_pretrained(
                self.model_name
            )
            self._model.to(self.device)
            self._model.eval()
            logger.info(
                "FinBERT loaded: model=%s device=%s",
                self.model_name,
                self.device,
            )
            return True
        except Exception as exc:  # pragma: no cover - depends on user env
            logger.warning(
                "Could not load FinBERT (%s). Fallback to legacy polarity.",
                exc,
            )
            return False

    @property
    def is_available(self) -> bool:
        return self._available

    def score_texts(self, texts: Iterable[str]) -> pd.DataFrame:
        """
        Score an iterable of strings with FinBERT.

        Returns
        -------
        pd.DataFrame with columns:
            sentiment_class, sentiment_polarity, sentiment_subjectivity,
            p_positive, p_neutral, p_negative
        """
        texts = [str(t) if t is not None else "" for t in texts]

        if not self._available:
            raise RuntimeError(
                "FinBERT is not available. Check `transformers` and `torch` "
                "installation, or use the legacy NewsSentimentExtractor."
            )

        torch = self._torch
        results: List[dict] = []

        with torch.no_grad():
            for start in range(0, len(texts), self.batch_size):
                chunk = texts[start : start + self.batch_size]
                enc = self._tokenizer(
                    chunk,
                    padding=True,
                    truncation=True,
                    max_length=self.max_length,
                    return_tensors="pt",
                ).to(self.device)
                logits = self._model(**enc).logits
                probs = torch.softmax(logits, dim=-1).cpu().numpy()

                # FinBERT label order: positive, negative, neutral
                labels = self._model.config.id2label
                idx_pos = self._label_index(labels, "positive")
                idx_neg = self._label_index(labels, "negative")
                idx_neu = self._label_index(labels, "neutral")

                for p in probs:
                    p_pos = float(p[idx_pos])
                    p_neg = float(p[idx_neg])
                    p_neu = float(p[idx_neu])
                    polarity = p_pos - p_neg
                    subjectivity = 1.0 - p_neu
                    if p_pos >= max(p_neg, p_neu):
                        cls = "positive"
                    elif p_neg >= max(p_pos, p_neu):
                        cls = "negative"
                    else:
                        cls = "neutral"
                    results.append(
                        {
                            "sentiment_class": cls,
                            "sentiment_polarity": polarity,
                            "sentiment_subjectivity": subjectivity,
                            "p_positive": p_pos,
                            "p_neutral": p_neu,
                            "p_negative": p_neg,
                        }
                    )

        return pd.DataFrame(results)

    @staticmethod
    def _label_index(id2label: dict, target: str) -> int:
        for idx, name in id2label.items():
            if str(name).lower().startswith(target):
                return int(idx)
        # Fallback: assume FinBERT default ordering
        order = {"positive": 0, "negative": 1, "neutral": 2}
        return order[target]

    def rescore_csv(
        self,
        input_path: str,
        output_path: str,
        text_columns: Optional[Iterable[str]] = ("title", "text"),
    ) -> pd.DataFrame:
        """
        Read a news CSV, re-score its sentiment with FinBERT, and write
        a new CSV. Returns the re-scored DataFrame.
        """
        in_path = Path(input_path)
        out_path = Path(output_path)
        out_path.parent.mkdir(parents=True, exist_ok=True)

        logger.info("Loading %s for FinBERT re-scoring", in_path)
        df = pd.read_csv(in_path)

        # Build text input: concatenate title + text when possible
        text_col_candidates = [c for c in (text_columns or ()) if c in df.columns]
        if not text_col_candidates:
            text_col_candidates = ["title"] if "title" in df.columns else []
        if not text_col_candidates:
            raise ValueError(
                "News CSV has neither 'title' nor 'text' columns; cannot score."
            )

        combined = df[text_col_candidates].fillna("").agg(" ".join, axis=1)

        if not self._available:
            logger.warning(
                "FinBERT unavailable; copying original CSV to %s unchanged.",
                out_path,
            )
            df.to_csv(out_path, index=False)
            return df

        scored = self.score_texts(combined.tolist())

        # Replace columns (keep originals as `*_legacy` for audit)
        for col in (
            "sentiment_class",
            "sentiment_polarity",
            "sentiment_subjectivity",
        ):
            if col in df.columns:
                df[f"{col}_legacy"] = df[col]

        df["sentiment_class"] = scored["sentiment_class"].values
        df["sentiment_polarity"] = scored["sentiment_polarity"].values
        df["sentiment_subjectivity"] = scored["sentiment_subjectivity"].values
        df["sentiment"] = scored["sentiment_class"].values

        df.to_csv(out_path, index=False)
        logger.info(
            "Wrote FinBERT-rescored CSV (%d rows) -> %s",
            len(df),
            out_path,
        )

        self._log_distribution_diff(df)
        return df

    @staticmethod
    def _log_distribution_diff(df: pd.DataFrame) -> None:
        if "sentiment_class_legacy" not in df.columns:
            return
        legacy = df["sentiment_class_legacy"].value_counts(normalize=True)
        new = df["sentiment_class"].value_counts(normalize=True)
        logger.info("Legacy class distribution: %s", legacy.to_dict())
        logger.info("FinBERT class distribution: %s", new.to_dict())
        try:
            corr = np.corrcoef(
                df["sentiment_polarity_legacy"].astype(float),
                df["sentiment_polarity"].astype(float),
            )[0, 1]
            logger.info("Polarity correlation (legacy vs FinBERT): %.4f", corr)
        except Exception:
            pass


__all__ = ["FinBERTSentimentExtractor"]
